inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
    - 'Gemfile*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Layout:
  Enabled: false

Naming:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false